language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - cd morf-python-api && pip install -e .

#sudo: required
#
#before_script:
#  - chmod -R +x ./morf-python-api/morf/
#

script: pytest

