language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
sudo: required
before_script:
  - chmod -R +x ./morf-python-api/morf/
#script:
#  - echo "script start"
#  - ./morf-python-api/morf/tests/test_s3_utils.py

