theme: jekyll-theme-minimal
kramdown:
  auto_ids: true # Auto-generate ID's for headings

description: > # this means to ignore newlines until "baseurl:"
  The MOOC Replication Framework.

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html